---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: argo
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/red512/triton-gitops
    targetRevision: HEAD
    path: helm/kagent-helm-chart
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: "latest"
        - name: env.LLM_PROVIDER
          value: "openai"
        - name: env.AGENT_MODE
          value: "orchestrator"
        - name: env.MAX_AGENTS
          value: "10"
  destination:
    server: https://kubernetes.default.svc
    namespace: triton
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true